module.exports = {
  MAIN_SERVER_PORT: process.env.MAIN_SERVER_PORT || 5000,
  SIGNALING_SERVER_PORT: process.env.SIGNALING_SERVER_PORT || 5001,
  PEER_SERVER_PORT: process.env.PEER_SERVER_PORT || 5002
}
